AllCops:
  Exclude:
    - 'spec/spec_helper.rb'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Metrics/AbcSize:
  Exclude:
    - 'spec/**/*'

Documentation:
  Enabled: false

Style/GuardClause:
  Enabled: false

Metrics/LineLength:
  Max: 100

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/MethodLength:
  Max: 15